### ISSUE TITLE
Kafka fails due to inability to load snappy library

### ISSUE THREAD

**Issue by joshschl** [OpenBMP/docker#10]
docker exec openbmp_kafka tail -f /var/log/kafka.log
....
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.2-5395f0cd-f2e4-4d77-ae88-69b6bb215bae-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.2-5395f0cd-f2e4-4d77-ae88-69b6bb215bae-libsnappyjava.so)

This error is then seen repeatedly:

2017-05-19 22:44:23,552] ERROR [Replica Manager on Broker 0]: Error processing append operation on partition openbmp.bmp_raw-1 (kafka.server.ReplicaManager)
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy

**Comment by TimEvens** [comment]
I'll be building the AIO which has an upgraded kafka version, which should fix this issue.  I'll send a note when that container has been published.

**Comment by bugtoo** [comment]
Hi @TimEvens, while it works on the aio container, it looks like the problem is still present on the latest kafka container - the issue is caused by missing glibc dependency on the base alpine used on the container. I've been able to workaround the issue by changing the base container image to frolvlad/alpine-glibc.

**Comment by xubo245** [comment]
Have you fixed this issue?

**Comment by TimEvens** [comment]
@xubo245 , yes as of today.  Kafka has been upgraded to 1.0.1 as well.

**Comment by xubo245** [comment]
ok, my problem also was fixed
